server {
    listen 8080;
    server_name localhost;
    root ./test_www/html;
    
    location /api {
        root ./test_www/backend;
        index index.php index.html;
        allow_methods GET POST;
    }
    
    location /images {
        root ./test_www/static;
	index test.html;
        allow_methods GET;
    }
}
