server {
    listen 8080;
    server_name site1;
    location / {
        index tests/server1.html;
    }
}

server {
    listen 8080;
    server_name site2;
    location / {
        index tests/routes.html;
    }
}
