#Multiple servers with different ports
server {
	server_name server1;
	listen 1234;
	
	location / {
		allow_methods GET;
		index tests/server1.html;
	}
}

server {
	server_name server2;
	listen 1235;
	
	location / {
		index tests/server2.html;
	}
}

#Multiple servers with different hostnames
server {
	server_name sameport1;
	listen 1236;

	location / {
		index tests/sameport1.html;
	}
}

server {
	server_name sameport2;
	listen 1236;

	location / {
		index tests/sameport2.html;
	}
}

#Default error page and body limit
server {
	server_name errorandbody;
	listen 1237;
	error_page 404 custom404.html;
	client_body_size 10;

	location / {
	}
}

#Routes and default file
server {
	server_name routes;
	listen 1238;

	location / {
	}
	
	location /someLocation/ {
		root tests/;
		index routes.html;
	}
}

#Allowed methods
server {
	server_name methods;
	listen 1239;
	error_page 405 tests/custom405.html;
	
	location / {
		allow_methods GET;
		index tests/methods.html;
	}
	
	location /dumpster/ {
		allow_methods POST DELETE;
		index tests/methods.html;
	}
}

#CGI
server {
	server_name cgiserver;
	listen 1240;
	location / {
		cgi_ext .py;
		cgi_path /usr/bin/python3;
	}
}

# Redirect & Autoindex
server {
	server_name extraserver;
	listen 1241;
	
	location /google {
		return 301 http://www.google.com;
	}

	location /tests/ {
		autoindex on;
	}
}

# Evaluation server for the exercise
server {
	server_name eval;
	listen 1250;
	client_body_size 100;

	# / must answer to GET request ONLY
	location / {
		allow_methods GET;
		index index.html;
	}

	# Any file with .bla extension must answer to POST by calling cgi_tester
	# regex location (match URIs ending with .bla)
	location ~ \.bla$ {
		cgi_ext .bla;
		cgi_path ./cgi_tester;
		allow_methods GET POST;
	}

	# /post_body must accept POST with maxBody 100
	location /post_body {
		allow_methods GET POST;
	}

	# /directory/ serves from YoupiBanane and uses youpi.bad_extension as index
	location /directory/ {
		allow_methods GET;
		root YoupiBanane/;
		index youpi.bad_extension;
		autoindex off;
	}
}
